export type ApiData = {
  server: string;
  client: string;
  value: string;
};

export const apiData = [
  { server: "customer-management", client: "chopin", value: "1019360" },
  { server: "risk-profiler", client: "chopin", value: "882085" },
  { server: "opportunity-knocks-service", client: "chopin", value: "798420" },
  { server: "customer-management", client: "account-api-gw", value: "709426" },
  { server: "chopin", client: "opportunity-knocks", value: "672637" },
  { server: "chopin", client: "continuous-cover", value: "630479" },
  {
    server: "customer-management",
    client: "opportunity-knocks",
    value: "366012",
  },
  { server: "account-api-gw", client: "?", value: "362128" },
  {
    server: "opportunity-knocks-service",
    client: "account-api-gw",
    value: "128753",
  },
  {
    server: "opportunity-knocks-service",
    client: "idiophone",
    value: "115631",
  },
  { server: "payments", client: "chopin", value: "103916" },
  {
    server: "customer-management",
    client: "ml-ncc-outbound-leads-pre-aggregations",
    value: "97135",
  },
  { server: "data-mill", client: "risk-profiler", value: "95641" },
  { server: "customer-management", client: "data-mill", value: "94983" },
  { server: "chopin", client: "account-api-gw", value: "86260" },
  { server: "customer-management", client: "full-contact", value: "76090" },
  { server: "chopin", client: "ernie", value: "61091" },
  { server: "payments", client: "continuous-cover", value: "45803" },
  { server: "chopin", client: "marketing-contribution", value: "34174" },
  { server: "customer-management", client: "idiophone", value: "25974" },
  { server: "data-mill", client: "chopin", value: "25207" },
  { server: "customer-management", client: "flexor", value: "21540" },
  {
    server: "opportunity-knocks-service",
    client: "continuous-cover",
    value: "18395",
  },
  { server: "chopin", client: "idiophone", value: "15140" },
  {
    server: "customer-management",
    client: "actionable_rfq_producers",
    value: "12766",
  },
  { server: "customer-management", client: "continuous-cover", value: "12486" },
  { server: "chopin", client: "polycomm", value: "10291" },
  { server: "circus", client: "chopin", value: "9569" },
  { server: "payments", client: "account-api-gw", value: "5983" },
  { server: "customer-management", client: "?", value: "5424" },
  { server: "customer-management", client: "lead-router", value: "3083" },
  { server: "customer-management", client: "pahs", value: "2480" },
  { server: "chopin", client: "flexor", value: "1772" },
  {
    server: "partner-authenticated-handover-service",
    client: "external-agent-backend",
    value: "767",
  },
  { server: "customer-management", client: "wholesale-service", value: "674" },
  {
    server: "opportunity-knocks-service",
    client: "sb-indicative-pricing",
    value: "661",
  },
  {
    server: "opportunity-knocks-service",
    client: "external-agent-backend",
    value: "189",
  },
  { server: "payments", client: "sb-indicative-pricing", value: "131" },
  { server: "chopin", client: "release-test", value: "108" },
  { server: "chopin", client: "external-agent-backend", value: "73" },
  { server: "customer-management", client: "customer-management", value: "20" },
  { server: "payments", client: "release-test", value: "16" },
  { server: "chronicle", client: "cerity", value: "13" },
  { server: "chopin", client: "chronicle", value: "13" },
  { server: "data-mill", client: "release-test", value: "13" },
  { server: "risk-profiler", client: "release-test", value: "13" },
  { server: "circus", client: "circus-demo-app", value: "6" },
  { server: "customer-management", client: "chronicle", value: "5" },
  { server: "simply-proxy-service", client: "acturis", value: "1" },
] as ApiData[];
